# Generated by Django 5.1 on 2024-08-27 08:13

from django.db import migrations

def set_default_order_status(apps, schema_editor):
    Order = apps.get_model('ecommerce', 'Order')
    Order.objects.filter(order_status__isnull=True).update(order_status='active')

class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_order_order_status'),
    ]

    operations = [
        migrations.RunPython(set_default_order_status),
    ]

