# Generated by Django 5.1 on 2024-08-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20240827_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('active', 'active'), ('completed', 'completed'), ('canceled', 'canceled')], default='active', max_length=10),
        ),
    ]
