# Generated by Django 5.1 on 2024-08-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_address_disabled_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='disabled_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
